on: [push]
name: "PHP-all-sys"

jobs:
  bindings_test:
    name: Bindings lints and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install libraries
        run: sudo apt-get -y install libbpfcc-dev
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --bin ddog_instructions_events
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/release/ddog_instructions_events
      
      # - uses: actions-rs/clippy-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     args: --all-features
      # - name: Run cargo check
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: check
      # - name: Run cargo test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      # - name: Install php-sys-build cargo bin 
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: --path ./sys-build
      # - name: Run php-sys-build - to compare the output
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: php-sys-build
      # - name: Run php-sys-build - to compare the output
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      # - name: Verify generated code matches committed code
      #   run: git add -A && git diff --staged --exit-code || true # temporarily allow failure
